### ISSUE TITLE
P-UAE documentation

### ISSUE THREAD

**Issue by CuttleFishJones8652** [libretro/docs#100]
Need help with P-UAE documentation.

@thatman84 pretty sure you have experience with this core

**Comment by thatman84** [comment]
I have spent the last hour trying to get setup on windows and Android without success. :)

The mouse emulations really is almost unusable. R button on gamepad can be used to lower speed but not by much.

I did have this working but it was on a custom core at the below link. This link also provides the best write up of the core I have come across by a long way.

http://lindqvist.synology.me/wordpress/?page_id=182

I may not be able to go down this rabbit hole for a while. I will look at other docs stuff this week
