### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by thatman84** [libretro/docs#105]
# First and foremost consider this:
- Only documentation related issues should be filed here. Not RetroArch bugs, or core bugs, or game bugs, or build errors.
- Before reporting a 404, refresh the doc a few times.

## Documents

https://docs.libretro.com/library/openlara/

**Comment by Hedonium** [comment]
Which images in particular? I'm not seeing anything wrong on my end. 🙁

**Comment by thatman84** [comment]
Under the how to start section... I am on a mobile though. Heres a screeny. I will go look at the md file now and see what the links are
![screenshot_20180428-190246](https://user-images.githubusercontent.com/26202064/39399522-fda5adf4-4b16-11e8-87d1-cd71a0ffab4d.png)

**Comment by thatman84** [comment]
These.  The image to download the Tomb Raider content is from the template it seems.

![](image\core\all\download.png) </center> - 
Select 'Tomb Raider', then select 'tombraider1-demo.zip'. This should download and extract this file to RetroArch's Downloads directory. <center>
 ![](image\core\folder\screenshot_name.png) </center> - Go back to RetroArch's main menu screen. Select 'Load Content', then 'Downloads'. 
<center> ![](image\core\all\load.png) </center> <center> ![](image\core\all\downloads.png) </center>

**Comment by Hedonium** [comment]
Ok. I forced Firefox to show the broken image symbols. I see the issue now.

Are you okay with me removing the image links? I removed them from the core template since they were bloating the docs.

**Comment by thatman84** [comment]
Sure I remember some groaning about repetition in the core docs. Either way
its fine with me.
