### ISSUE TITLE
pcsx_rearmed - BIOS Info Incorrect

### ISSUE THREAD

**Issue by MajorDangerNine** [libretro/docs#134]
## Documents

https://docs.libretro.com/library/pcsx_rearmed/

### Proposed changes

******

#### Change 1

The BIOS information there is incorrect and should be like below.

*****

|   Filename    |    Description         |              md5sum              |
|:-------------:|:----------------------:|:--------------------------------:|
| scph101.bin | psone-45a - Version 4.5 05/25/00 A | 6E3735FF4C7DC899EE98981385F6F3D0
| scph7001.bin | ps-41a - Version 4.1 12/16/97 A | 1E68C231D0896B7EADCAD1D7D8E76129
| scph5501.bin | ps-30a - Version 3.0 11/18/96 A | 490F666E1AFB15B7362B406ED1CEA246
| scph1001.bin | ps-20a - Version 2.0 05/07/95 A | DC2B9BF8DA62EC93E868CFD29F0D067D

*****

And as a verification that this is correct, here is an entry that lists them in the libretro core's GitHub.

https://github.com/libretro/pcsx_rearmed/blob/master/frontend/libretro.c#L1921

*****

#### Change 2

I would also add the following to the end of the **Attention** part.

*****

If more than one BIOS is supplied, then the emulator will default to the latest revision available.

*****

Thank you for your time and all the hard work that goes into RetroArch. I would've done this myself, but I'm not up for learning how to use GitHub beyond filing issues or editting open project wikis.

**Comment by RobLoach** [comment]
Looks like they could be updated in https://github.com/libretro/libretro-database/blob/master/dat/BIOS.dat#L165-L168 too .

Good catch!

**Comment by MajorDangerNine** [comment]
I failed to notice that the emulator now has support for all uppercase and all lowercase of the filenames as of 17 days ago, which is useful for those on case-sensitive OSes such as Linux.

I corrected the filenames so that they are lowercase as that will allow for dual BIOS usage of **scph5501.bin** with lr-beetle-psx & lr-beetle-psx-hw, which both only have support for lowercase BIOS filenames currently, or at least as far as I can tell from my brief look at the GitHub page.

**Comment by thatman84** [comment]
@retro-wertz I noticed you were doing edits to PCSX-rearmed. Is this something you have or would look at?

**Comment by ghost** [comment]
i think whichever bios doesnt matter.

currently these are the primary search keywords used to search for bios file
SCPH101", "SCPH7001", "SCPH5501", "SCPH1001

if non of those are detected, it defaults to search for any file in system directory starting with "scph" and use that as a bios file, before falling back to HLE (builtin high-level emulation) for its bios file.

**Comment by ghost** [comment]
ok updated...

**Comment by markwkidd** [comment]
@hizzlekizzle this could be closed

**Comment by idn400189-design** [comment]
> ## Documents
> https://docs.libretro.com/library/pcsx_rearmed/
> 
> ### Proposed changes
> #### Change 1
> The BIOS information there is incorrect and should be like below.
> 
> Filename	Description	md5sum
> scph101.bin	psone-45a - Version 4.5 05/25/00 A	6E3735FF4C7DC899EE98981385F6F3D0
> scph7001.bin	ps-41a - Version 4.1 12/16/97 A	1E68C231D0896B7EADCAD1D7D8E76129
> scph5501.bin	ps-30a - Version 3.0 11/18/96 A	490F666E1AFB15B7362B406ED1CEA246
> scph1001.bin	ps-20a - Version 2.0 05/07/95 A	DC2B9BF8DA62EC93E868CFD29F0D067D
> And as a verification that this is correct, here is an entry that lists them in the libretro core's GitHub.
> 
> https://github.com/libretro/pcsx_rearmed/blob/master/frontend/libretro.c#L1921
> 
> #### Change 2
> I would also add the following to the end of the **Attention** part.
> 
> If more than one BIOS is supplied, then the emulator will default to the latest revision available.
> 
> Thank you for your time and all the hard work that goes into RetroArch. I would've done this myself, but I'm not up for learning how to use GitHub beyond filing issues or editting open project wikis.
