### ISSUE TITLE
Combo Inputs

### ISSUE THREAD

**Issue by danielcarlosdasilva** [libretro/docs#155]
Hi. Some GBA games needs a multiple input to do a single action, like B+L toggles Medium Punch on some Fighting Games. There is a way to create a combo mapping to this things, like pressing X button toggles B+L?

**Comment by esoptron** [comment]
Hello. This isn't the proper place for this kind of issue.

Please close this issue and make a new one at 

https://github.com/libretro/RetroArch/issues
