### ISSUE TITLE
Error starting build

### ISSUE THREAD

**Issue by ghost** [libretro/docs#159]
Using Ubuntu 16.04 and following the README to install the required dependencies via pip3, I get an error trying to start the build:

```
$ mkdocs build
ERROR   -  Config value: 'markdown_extensions'. Error: Failed loading extension "codehilite(linenums=True)". 

Aborted with 1 Configuration Errors!
```

Any idea what's going on?

**Comment by ghost** [comment]
travis has the same problem: https://travis-ci.org/libretro/docs/jobs/443859171#L494

**Comment by alfrix** [comment]
it was a syntax problem
https://github.com/libretro/docs/commit/53edcc2f9fb27bd1b57d04314e4e15b9bcbd8a47

**Comment by markwkidd** [comment]
I have been able to build the docs as of today in msys2 so I think this is solved
