### ISSUE TITLE
Multilingual docs

### ISSUE THREAD

**Issue by lambolighting** [libretro/docs#162]
Libretro/RetroArch has appeared in so many different devices and it has started expanding to many more countries.

There are now people with not so many computer skills or English fluency using it and i believe the docs should be translated in other languages as well in order to help them out.

I can help with the Greek translation but i want some help on how if it is possible to translate the docs.

**Comment by markwkidd** [comment]
Unfortunately our documentation tool -- mkdocs -- does not support managing translations in an automated way although there is an active discussion in their repository about improving this: https://github.com/mkdocs/mkdocs/issues/211

In the meantime, this means that the only workflow is manual -- individual docs files could be translated by hand and added to this repository as if they are new documents.

**Comment by fpscan** [comment]
I guess we can close this one, since it's multilingual docs is not possible, least now, neither with `mkdocs` or `mkdocs-material` 

Manually setting multilingual docs might be hard thing to maintain and perform. I will take a look on this and when I found a workaround I will perform.
