### ISSUE TITLE
FCEUmm doc additions/suggestions

### ISSUE THREAD

**Issue by retro-wertz** [libretro/docs#163]
this should give general idea of the options needing descriptions: re-word if needed to fit etc.

```
- Color Palette - raw	 RAW palette is used in combination with nes-decoder shader to give colors based off on bisqwit's NES palette generator and applies either an FCC color conversion matrix or specific Sony US matrix
- Sound Quality		 Enables high/higher sound quality for games using expansion audio (MMC5, VRC6, VRC7, Namco, Sunsoft). Use Low for slower devices. 
- Swap Duty Cycles	 Replicates the sound of some famiclones that have duty cycles swapped for square channels. A quick sound comparison is in Contra's sound effect when shooting with normal bullets.
- Zapper Mode		 Pointer allows zapper to be used for touch-devices, but still can be used with regular mouse. Pointer and Mouse mode movement behaves differently with different input driver so user can choose which movement feels natural to them.
- Overclocking		 Overclocks the NES using PPU method to minimize ingame slowdowns of some games.
			 Contra Force needs VBlank mode (stage 3 slowdowns). Choose which ever minimizes slowdowns without image distortion.


- Ms.Pacman(Tengen) issue - 	 this is a mirroring issue or some roms. a crc check has since been added to fix this rom with wrong headers set. 
```

**Comment by esoptron** [comment]
Your suggestions have been implemented in PR #164 

I removed the Ms.Pacman entry from the compatibility table since the issue have been fixed. Most of the compatibility tables in the core docs are just ancient information copy and pasted from the Libretro Wiki.

**Comment by retro-wertz** [comment]
Some additions:
Supports the following controls using mouse/pointer device:
nes_controllers:(manual and auto selection available) <-
Arkanoid Paddle

famicom controllers:(auto selected by crc for now)
Arkanoid Paddle
Bandai Hyper Shot Gun (for Space Shadow) <- this is not to be confused for Konami Hyper Shot
Oeka Kids Tablet

also FCEUmm supports 4 players for NES and Famicom (detected by crc) <- not sure where in the entry this should be.

**Comment by esoptron** [comment]
PR #175 

Added Arkanoid Paddle for the NES to the User 2 device types section. https://buildbot.libretro.com/docs/library/fceumm/#user-2-device-typess

The Famicom controllers that can't be manually selected were given their own section. https://buildbot.libretro.com/docs/library/fceumm/#other-famicom-controllers

Added a section explaining Multitap support. https://buildbot.libretro.com/docs/library/fceumm/#multitap-support

Updated the controllers graph section to include the Arkanoid Paddle, Bandai Hyper Shotgun and Oeka Kids Tablet. https://buildbot.libretro.com/docs/library/fceumm/#controllers-graph

I'll add note for "gamepad UP to move forward, gamepad B to throw grenade" soon.

**Comment by retro-wertz** [comment]
it looks better that if I was to make it :p

**Comment by esoptron** [comment]
I'm closing this. Reopen if you have more suggestions.

**Comment by retro-wertz** [comment]
i dont mind, actually forgot to close this for that reason. i havent been
able to update core since im stuck with implementing the other
controls/devices of the core.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
