### ISSUE TITLE
NEC - PC-98 (Neko Project II Kai) BIOS directory should be 'np2kai'

### ISSUE THREAD

**Issue by Accellular** [libretro/docs#168]
## Documents

docs/library/neko_project_ii_kai.md

### Proposed changes
in the sentence
> !!! attention These firmware files need to be in a directory named **'np2'** in the frontend's system directory.

**'np2'** 
should be: 
**'np2kai'**

I have tested it and found out that if using 'np2' folder, the Japanese texts in the game cannot display correctly.

### References
Here is the explanation from the author of the core:
[マルチエミュレータシステム『RetroArch』の解説です。]( http://domisan.sakura.ne.jp/article/retroarch/retroarch.html)

> C:¥ユーザー¥（ユーザー名）¥AppData¥Roaming¥RetroArch¥system を開き、
「np2kai」フォルダを作成する。

**Comment by hizzlekizzle** [comment]
Thanks for letting us know :)
