### ISSUE TITLE
docs link on libretro.com footer is broken

### ISSUE THREAD

**Issue by markwkidd** [libretro/docs#178]
The documentation link in the footer of the website template is dead.

Here's the link I'm referring to: ![screenshot 2018-12-17 11 15 43](https://user-images.githubusercontent.com/19554678/50099942-4485b100-01ed-11e9-8b0b-1db0a97860a6.png)

**Comment by alfrix** [comment]
https://github.com/libretro/www.retroarch.com

**Comment by markwkidd** [comment]
Thanks, done!
