### ISSUE TITLE
create LED driver docs

### ISSUE THREAD

**Issue by markwkidd** [libretro/docs#187]
At present there is no documentation about how the LED drivers work from the user perspective or from the coding perspective.

The best starting point I know of for creating docs would be to look at the existing LED drivers in RetroArch and work backwards towards a description of how the LED API works: https://github.com/libretro/RetroArch/tree/master/led/drivers

I don't know anything about this topic at the moment but I'm creating this issue partly because I'm willing to learn and help create docs. I'm also creating this issue in the hopes that someone else who already knows the answers will appear and get this started 😸 

If I do wind up starting this from scratch, it take a little while for me to get back to it but having this issue will help me not loose track.

**Comment by gouchi** [comment]
@markwkidd @fpscan This issue can be closed, thanks to @zoltanvb.

Thank you.
