### ISSUE TITLE
PSA: Back in business

### ISSUE THREAD

**Issue by CuttleFishJones8652** [libretro/docs#194]
Sorry for the long absence.

Ready to start contributing again.

**Comment by thatman84** [comment]
Glad to see your hat back in the ring !

What you thinking of working on? I just got a ubuntu VM setup with git and docs so i can be helpful again (dont hold me to that still busy with RLS)

**Comment by CuttleFishJones8652** [comment]
Everything core documentation related. I'm looking at every core repository and seeing whether they have  new features that haven't been added to the documentation yet.
