### ISSUE TITLE
Compilation fails to start

### ISSUE THREAD

**Issue by ajshell1** [libretro/docs#199]
This is a separate issue from https://github.com/libretro/docs/issues/159

This is the error I get:

ERROR   -  Config value: 'markdown_extensions'. Error: extendMarkdown() takes 2 positional arguments but 3 were given 

Aborted with 1 Configuration Errors!

I'm on Antergos Linux, using AUR versions of all dependencies (because I know from experience that combining PIP and rolling-release distros is asking for trouble.

I don't know how to fix this because I can't compile to documentation to read it.

**Comment by markwkidd** [comment]
> I don't know how to fix this because I can't compile to documentation to read it.

What is your ultimate purpose? Are you trying to contribute to the docs or simply to read them?

If you are just trying to read the libretro documentation, you can do so at http://docs.libretro.com.

**Comment by fpscan** [comment]
> This is a separate issue from #159
> 
> This is the error I get:
> 
> ERROR - Config value: 'markdown_extensions'. Error: extendMarkdown() takes 2 positional arguments but 3 were given
> 
> Aborted with 1 Configuration Errors!
> 
> I'm on Antergos Linux, using AUR versions of all dependencies (because I know from experience that combining PIP and rolling-release distros is asking for trouble.
> 
> I don't know how to fix this because I can't compile to documentation to read it.

This might not be an active issue but if you encounter again, it's working fine now. make sure you have pip.

`pip install mkdocs-material`

then fork and `git clone https://github.com/YOURNAME/docs.git`

You’d want to add a Git remote that points back to the original repository, like this: `git remote add upstream https://github.com/libretro/docs.git`

To create a new branch and check it out:

`git checkout -b <my-changes-1>`

After making changes, you can use `mkdocs serve` in docs folder it will create localhost: so you can see your changes live.

then:
`git push origin new-feature`

edit: Github Desktop is also nice to use.
