### ISSUE TITLE
incorporate the retroarch.com "joypad autoconfig" article into the retropad doc

### ISSUE THREAD

**Issue by markwkidd** [libretro/docs#202]
There is some great material here that could be added to our existing RetroPad guide: https://www.retroarch.com/index.php?page=joypad-autoconfig

I can't take this project on at the moment.  Someone else is very free to or I may come back to this in the future and work on it myself :)

**Comment by hizzlekizzle** [comment]
Seems like a good plan. However, I'm pretty sure that's not OpenEmu's mapping window, but rather snes9x's(?).

**Comment by thatman84** [comment]
I cant find that page manually, i wonder if theres any other nice hidden
gems...

How did you find that one?
