### ISSUE TITLE
mkdocs.yml under the "For Users" section should be orgainsed in order of something like a guide.

### ISSUE THREAD

**Issue by ghost** [libretro/docs#26]
## Documents

mkdocs.yml

### Proposed changes

I want to reorganise this section so that it has a logical order. Essentially it should follow the order of a guide or tutorial meaning that it should start with installing and then move onto setting up, then cores and advance config should be moved backwards. I've made a pull request that has done this, please view and accept.

**Comment by CuttleFishJones8652** [comment]
Looks fine.

It will be merged eventually.

**Comment by ghost** [comment]
@Hedonium I am interest in writing and improving some of the documentation for using RetroArch, especially the getting started guides.

Would it be OK if my account gets permission to the repo?

**Comment by CuttleFishJones8652** [comment]
Send in pull requests and then TwinAphex will review and/or merge them.

**Comment by markwkidd** [comment]
What about moving the "For Users" section first, instead of after "For Developers"?

**Comment by CuttleFishJones8652** [comment]
Please close this issue and move the discussion to over here.

https://github.com/libretro/docs/issues/4

I want the discussion about mkdocs.yml to be all in one place. 🙂

**Comment by markwkidd** [comment]
@Hedonium is it OK to close this issue now?

**Comment by CuttleFishJones8652** [comment]
@markwkidd Yeah. I don't have permission to close it myself though. If there's any issues I made that would be better off closed, let me know.

**Comment by markwkidd** [comment]
Ah somehow I thought this was yours. @hizzlekizzle do you mind closing this, if you think it's OK?

**Comment by ghost** [comment]
I made this mostly as a reminder, I am finished with it personally.

Closing...
