### ISSUE TITLE
third-party libretro documentation to also keep up to date

### ISSUE THREAD

**Issue by markwkidd** [libretro/docs#310]
This issue was generated from the old TODO file.

- Move on to updating the RetroPie wiki when Libretro documentation is finished. https://github.com/RetroPie/RetroPie-Setup/wiki
- Move on to updating the Emulation General when Libretro documentation is finished. http://emulation.gametechwiki.com/index.php/Main_Page

**Comment by fpscan** [comment]
I am going to close this one for now.
