### ISSUE TITLE
Numerous broken image paths

### ISSUE THREAD

**Issue by jdgleaver** [libretro/docs#331]
While updating the gambatte documentation (PR #330), I noticed that PR #281 broke many image paths. It looks like a simple find/replace error, where the final directory slash was omitted. Most of the core documentation seems affected.

PR #330 fixes this for gamebatte, but I don't have time to go through the other files...

**Comment by markwkidd** [comment]
I see that I definitely mangled some paths. The mystery to me is why the paths that got screwed up aren't throwing warnings now too like the deprecated ones before. I'll clone this repo and try building it locally as soon as I have a chance. I'm hoping for a list of all affected files to make a plan.

**Comment by fpscan** [comment]
This the last one that had broken path https://github.com/libretro/docs/commit/3296e6e82b32d408d4ca7f0625c28df022f42e1f#diff-3c1bf97125e7bd5dc18388b775f87cbd 
There is no broken path for now but I will check it to be sure

```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /github/workspace/site 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - library/redream.md 
INFO    -  Documentation built in 41.61 seconds
```
