### ISSUE TITLE
Remove  Star Wars Arcade entry from 32x  compatibility issues.

### ISSUE THREAD

**Issue by Testsr** [libretro/docs#335]
## Documents

[Add a list of documents that should be changed here.]
compatibility/32x.md
picodrive.md
### Proposed changes

[What changes should be done to the documents.]
Remove Star Wars Arcade (PAL version) entry as this is now correctly emulated.

**Comment by Testsr** [comment]
Check

**Comment by orbea** [comment]
@Testsr Do you have a reference for this correct emulation? Where was it fixed?

**Comment by CuttleFishJones8652** [comment]
Yep, game works.

The compatibility info is based off of years old documentation so that glitch might have been fixed a long time ago.
