### ISSUE TITLE
Slash image is actually a backslash

### ISSUE THREAD

**Issue by feikname** [libretro/docs#366]
Affected files:
 * `docs/image/Button_Pack/Keyboard_Mouse/Keyboard_Black_Slash.png` 
 * `docs/image/Button_Pack/Keyboard_Mouse/Light/Keyboard_White_Slash.png`

Those show a backslash rather than a slash, which really confused me at first.

![Backslash image rather than slash](https://raw.githubusercontent.com/libretro/docs/master/docs/image/Button_Pack/Keyboard_Mouse/Dark/Keyboard_Black_Slash.png)

Mirroring the image should solve it.

**Comment by hizzlekizzle** [comment]
Thanks for the report. should be fixed now!
