### ISSUE TITLE
Core Options table or bold text?

### ISSUE THREAD

**Issue by thatman84** [libretro/docs#43]
#42 #32 

Are will still keeping the template format of core options or moving to the plain text format?

Edit just realised table format is not in the Core_Template.md

**Comment by HerbFargus** [comment]
I don't know if it matters all that much. personal preference really. depending on the screen size and how many core options there are the tables will scroll which can obscure the content. I figure first pass will be to get the content in, and then it will probably have a few iterations of improvement once have everything.

I don't have a preference for one or the other

**Comment by thatman84** [comment]
Fair enough. I will stick with the Table so there is a contrast.

Would you mind updating the google sheet with the ones you have planned...im in the process of Mednafen-lynx.md @herbfargus

**Comment by esoptron** [comment]
Using the table standard feels too restrictive. There's a bunch of core options that would be more easily explained by including an in-game screenshot . Using bold text leaves ample space to do so.

**Comment by thatman84** [comment]
Thats a good enough point for me to agree to use the bold text format instead.
Sometimes i have no clue what a core option will do and a screenshot would be a great help.

I will leave the issue open till the weekend then close and edit template+all core.md files
