### ISSUE TITLE
Add Last Updated date on core documentation

### ISSUE THREAD

**Issue by CuttleFishJones8652** [libretro/docs#44]
Write a mkdocs plugin that parses the git history of a core doc and prints out the time the core doc was last updated.

Like this

![image](https://user-images.githubusercontent.com/34848002/37837212-0478dba4-2e8b-11e8-82b6-a4ddb87f8fd4.png)

**Comment by thatman84** [comment]
Great idea

**Comment by CuttleFishJones8652** [comment]
Thanks.

Hopefully this will give end-users the idea that the documentation isn't set in stone and can always be improved.

**Comment by thatman84** [comment]
Asked for advice some advice in discord and here https://groups.google.com/forum/m/#!topic/mkdocs/0iij2vNZZwE

Edit: found an open issue at mkdocs repo and subscribed
https://github.com/mkdocs/mkdocs/issues/1408

**Comment by CuttleFishJones8652** [comment]
Added in https://github.com/libretro/docs/pull/349
