### ISSUE TITLE
Website docs - HTTP 404 error

### ISSUE THREAD

**Issue by fab1o** [libretro/docs#474]
This is my first time getting to know RetroArch. I went to the documentation but it's giving me 404.

https://docs.libretro.com/

Just wanted to let you know in case you haven't enountered this issue.

**Comment by hizzlekizzle** [comment]
Thanks, yeah, it seems to be a hosting issue.

**Comment by fpscan** [comment]
https://github.com/libretro/docs/pull/492 this is fixed
