### ISSUE TITLE
[Addition] Core overrides guide

### ISSUE THREAD

**Issue by markwkidd** [libretro/docs#48]
The RetroArch docs do not currently document the override system.

This Issue requests the creation of a document aimed at new users which explains the override system.

This Issue is inspired by a forums post: https://forums.libretro.com/t/auto-load-core-configs/11191/

**Comment by thatman84** [comment]
I will probably tackle this next but won't PR until it's had some feedback on my repo.

**Comment by thatman84** [comment]
On hold to see if this feature gets added 1st

https://github.com/libretro/RetroArch/issues/5100#issuecomment-327528604

**Comment by thatman84** [comment]
Can this now be closed?
https://docs.libretro.com/guides/overrides/

**Comment by markwkidd** [comment]
Seems like it. Thanks!
