### ISSUE TITLE
Netplay configuration options explained, Along with the rest of the RetroArch menu

### ISSUE THREAD

**Issue by Kaydron1000** [libretro/docs#502]
**Describe the bug**
"For User: Netplay" documentation does not describe all the different configuration options available to the user and how they effect Netplay session.

**Expected behavior/changes**
Expected to have all configuration options explained for how it effects a Netplay session. Possible further explanation on good ideas for Netplay settings such as ensure setting your session to private to prevent random people joining your Netplay session.

**Additional context**
I spent quite a few days trying to find information on setting up Netplay as 2 devices with 4 people playing. I was using 2 Raspberry pi4s with RetroPie installed. For some odd reason while browsing the RetroArch menu the network options did not have the following options visible "Request Device #" (where # = 1 to 16) I found out about this option from RetroArch Issue #10413 (I added details for other like myself). I was then able to find it in retroarch.cfg and update configuration manually. I loaded another image a few days later and the options were visible on the RetroArch menu, that made things a bit easier. Even with having configuration option now visible i couldn't find documentation on what all the different configuration items meant.

I am looking to contribute to some open source projects and this seems like a good place to start. The retro gaming projects have peaked my interest ever since we were highly encouraged to isolate ourselves :)
I read through getting started associated with the markdown information and Issue #297 looks like you are trying to stream line people like myself and @Clutz450 to be able to contribute. I have previously worked with repositories some for work (TortoiseHg and TortoiseSVN), but never interfaced with GitHub or any complex workflows. A large portion of my knowledge is C# with some python and i see most of your code base is C & C++ which is another reason why i thought documentation would be a good start especially with this project.

I was going to continue down the path of compiling the current documentation then create a branch by adding RetroArch: Configuration... It can start out as individual items but maybe increase to the full suite of the whole RetroArch menu. Ideally it would be nice to provide code documentation and scrape out summaries of these configurations then build the documentation as the code gets updated. Looking through the source i do not see any "docstrings" or many comments so do not think this is possible right now.

**Comment by fpscan** [comment]
Hi @Kaydron1000 thank you and welcome :) Make sure to join our Discord https://discord.gg/27Xxm2h if you have Discord account, there are really cool people know more stuff. Contributing docs really easy, you don't really have to build mkdocs or anything you can just simply follow this steps; fork, create branch, make your changes, push, pr. You can find me on discord with this tag gadsby#6752 , if you have more question. 

NetPlay is not much complicated in my opinion, you host and they join, however I am aiming to improve current documentation in future, currently working on something we are eager to make public.

So far I made this one as well https://www.youtube.com/watch?v=Z3CTuTx0nnc for introduction to netplay.

Full list:

https://docs.libretro.com/guides/netplay-faq/
https://docs.libretro.com/development/retroarch/netplay/
https://www.youtube.com/watch?v=Z3CTuTx0nnc
http://www.retroarch.com/?page=netplay

I am really excited to see your contributions! I also would like mention our other critical channels: https://www.reddit.com/r/RetroArch/ and https://forums.libretro.com/

**Comment by Kaydron1000** [comment]
Thanks so much for the resources i'll start digging in ... after work ... i need to get back to that :)
