### ISSUE TITLE
Giant icons and no content on Netplay Multiple Controllers Articles

### ISSUE THREAD

**Issue by OfficePop** [libretro/docs#519]
### Documents

https://docs.libretro.com/guides/netplay-faq/netplay-multiple-controllers

### Proposed changes

The article is currently unreadable with giant icons, no content, and broken navigation links all over the place. Confirmed this is an issue with both Chrome and Firefox.

**Comment by fpscan** [comment]
Can you check this one: https://docs.libretro.com/guides/netplay-multiple-controllers/

**Comment by OfficePop** [comment]
This works correctly now.
