### ISSUE TITLE
PCSX ReARMed - Possible wrong md5sum listed for scph1001.bin BIOS

### ISSUE THREAD

**Issue by lukemoore66** [libretro/docs#528]
https://docs.libretro.com/library/pcsx_rearmed/

md5sum is listed as:
scph1001.bin, Version 2.0 05/07/95 A, dc2b9bf8da62ec93e868cfd29f0d067d

My dump of this BIOS always returns 924e392ed05558ffdb115408c263dccf

As well as multiple other copies of this BIOS I have found elsewhere. Verified with sigcheck on Windows 10, as well as md5sum on Linux.

No copy of a ps1 bios I could find matches what is currently listed.

**Comment by acplr** [comment]
Actually the name of this BIOS is DTL-H1001. It confused me too. They should add a note about it.

**Comment by hizzlekizzle** [comment]
@acplr probably best to remove that link. It's not a good idea to link to copyrighted ROMs, including BIOSes.

**Comment by acplr** [comment]
@hizzlekizzle You're right. I deleted the link.

**Comment by zoltanvb** [comment]
This was fixed by https://github.com/libretro/docs/commit/0cada9aed167d29ccec1d71064d894aac0d071d6
