### ISSUE TITLE
Directory Configuration, Savefile and Savestate have their own location now by default

### ISSUE THREAD

**Issue by dantob** [libretro/docs#532]
>  Savefile and Savestate
>-----
>
> Last one you should consider changing are the save locations, by default it will place them in the same folder as your ROMS. If  you care about organisation you should change these to another folder.

This paragraph is probably not needed at all, by default I'm seeing
` Savefile ~/.config/retroarch/saves `
` Save State ~/.config/retroarch/states `

**Comment by fpscan** [comment]
> > ## Savefile and Savestate
> > Last one you should consider changing are the save locations, by default it will place them in the same folder as your ROMS. If  you care about organisation you should change these to another folder.
> 
> This paragraph is probably not needed at all, by default I'm seeing
> `Savefile ~/.config/retroarch/saves`
> `Save State ~/.config/retroarch/states`

Thank you for this! I will re-visit that line, some system like nx has folders under `core/...` folder and psc's save folder is also in different folder.

**Comment by dantob** [comment]
please check this, it turns out my system had a pre-configured system .cfg file in `/etc` that might have overridden the defaults

**Comment by hizzlekizzle** [comment]
RetroArch should never automatically look in /etc. That config is just there for reference, AFAIK.

**Comment by dantob** [comment]
it was configured by the distro packager in  `.xinitrc`

```
# Autostart Retroarch
exec /usr/bin/retroarch --appendconfig=/etc/retroarch-standalone.cfg -v 2>&1 >&/home/retroarch/debug.log
```
