### ISSUE TITLE
Hyperlinks in the psvita installation guide lead to a 404

### ISSUE THREAD

**Issue by TheSmallBlue** [libretro/docs#595]
**Describe the bug**
If you go to [the psvita installation guide](https://docs.libretro.com/guides/install-psv/) and you try to download the VPKs or the data files, you'll either get a page that does nothing and instantly closes, or a 404 page.

**Expected behavior/changes**
The hyperlinks should lead to their respective destinations. The first and second one should lead to the stable and nightly vpk downloads, and the fourth and fifth should lead to the data files. The sixth should lead to the bundle file. None of these do so

**Additional context**
Files must've been moved to another url and this specific page hasn't been updated, don't think its a big issue.
![b491lF1Ct6](https://user-images.githubusercontent.com/24967815/115805439-5da15c80-a3bb-11eb-9b69-e9ae73bcbb5c.gif)

**Comment by TheSmallBlue** [comment]
Clarification after checking it out a bit more in depth:
Only the links to the stable data file and the bundle file return 404s. The stable data file one is because it tries to get the "RetroArch_data" file from `buildbot.libretro.com/stable/1.9.0/playstation/vita/`, when no such file exists there. In fact, both data and apk files links direct to 1.9.0, when the latest version is 1.9.1. `buildbot.libretro.com/stable/1.9.1/playstation/vita/` does have RetroArch_data, so the fix is as simple as changing one number in the redirection links. And removing the bundle header completely I guess.

**Comment by fpscan** [comment]
I'll revisit the PS Vita installation. I will also update the video, Vita installation changed to become less hassle. Thank you.
