### ISSUE TITLE
Wrong information in Handy (Atari Lynx)'s docs

### ISSUE THREAD

**Issue by Auster-South-Anemoi** [libretro/docs#614]
**Describe the bug**
The page mentions the BIOS image is optional for emulating Atari Lynx games.

**Expected behavior/changes**
The BIOS is actually required for emulating these games.

**Additional context**
Doc page: https://docs.libretro.com/library/handy/#bios

**Comment by fpscan** [comment]
https://github.com/libretro/docs/commit/c7f93af0aa5a4f863018174b1acee97eeae3fa1d
