### ISSUE TITLE
Ads Mess Up Wiki Pages

### ISSUE THREAD

**Issue by keo13579** [libretro/docs#615]
![image](https://user-images.githubusercontent.com/49461342/121542315-ab0a7500-c9cd-11eb-86f3-ebef7985a82b.png)
I expected the wiki to be normal, but these ads are interrupting the text.

Edit: This only seems to work on the DeSeMume page, not sure why.

**Comment by fpscan** [comment]
https://github.com/libretro/docs/commit/c8aed7a15742e6d3009302037b8508b998df683e
