### ISSUE TITLE
[retroarch.com] replace "joypad driver" and "joypad configuration" with "controller"

### ISSUE THREAD

**Issue by markwkidd** [libretro/docs#646]
The English translation has standardized on the term Controller in the RetroArch interface. Docs that use joypad for those functions need to be updated.

I have made many of these updates here in the docs repo, but could someone remind me what the process is to update the content of the retroarch.com website?

**Comment by fpscan** [comment]
Retroarch.com is private repo, let me know the changes so I can make it and refresh the server.

**Comment by markwkidd** [comment]
# https://retroarch.com/

<img width="352" alt="Screenshot 2021-08-18 16 13 16" src="https://user-images.githubusercontent.com/19554678/129965959-4acf506d-dc9a-44ba-b54b-57310c305c15.png">

**Existing Horizontal scroller panel**: "Joypad Auto Configuration"

**New panel title**: Automatic Controller Configuration

**New text**
Common game controllers are automatically configured when plugged in, just like a real console.

Ideal for multiplayer games when a friend brings their own controller!

You can also configure controllers manually to assign special actions to button combos.

**Comment by markwkidd** [comment]
# https://www.retroarch.com/index.php?page=faq

There are two FAQs that need to be edited. I'll include the corrected text below. @fpscan please note that I have corrected some typos and made updates in addition to changing 'joypad' to 'controller', so I suggest that you copy and paste from my text directly.

## How do I download controller profiles?

The most up-to-date set of controller profiles compiled by RetroArch can be downloaded and updated from the menu. Go to Main Menu->Online Updater->Update Autoconfig Profiles to get the latest pack.


## How do I create a new autoconfig profile for my controller?

If your joypad is not recognized by RetroArch even after updating the profiles, you can generate a profile from the menu. The first step is to proceed to a manual mapping of your pad. For this, unplug all the other controllers, and use Settings->Input->User 1 Binds->User 1 Bind All.

Make sure that your mapping is perfect by testing every button in the menu and in some games. Finally, use Settings->Inputs->User 1 Binds->User 1 Save Autoconfig and the controller profile will be saved to your disk. You can now do a Settings->Inputs->User 1 Binds->User 1 Bind Default All to reset the manual settings. Otherwise they would take precedence over the profile you generated. Unplug your controller and then re-plug it. See if it is automatically configured.

Users can share new and corrected controller profiles with the RetroArch team via the controller autoconfig repository on github at https://github.com/libretro/retroarch-joypad-autoconfig.

**Comment by markwkidd** [comment]
I will work on the rest of the website as soon as I get more time

**Comment by markwkidd** [comment]
# https://www.retroarch.com/index.php?page=interface

**I'm only including changed portions of this page below**

## The graphical interface
**Suggest changing this heading to `User interface` or `Graphical user interface`**

Ozone is the default graphical interface of RetroArch. It is optimized for navigation with a game controller and incorporates a database-driven playlist system to browse your collection with metadata and thumbnails. The graphic interface also allows you to tweak settings and perform other customizations on a game-by-game basis.

## Integrated downloads

* Change "Joypad profiles: default mapping for common joypads to work out of the box" to "Controller profiles: automatic mappings for common gamepads, joysticks, and other game controllers"
* Change "A few free games and homebrews" to "**Content downloader**: Free games and other downloadable content"

## Fully joypad driven
**Change to: "Fully controller driven"**

In the RetroArch GUI, game controllers are the preferred way to navigate. You can perform every action using the controller, including launching games or triggering the RetroArch menu from the active game.

When you need to type text in the settings interface, a multilanguage On Screen Keyboard will be displayed to let you type words and passwords with your controller or touchscreen.

The menu has been designed as an immersive experience: you will not have to switch from your controller to your keyboard to perform actions using the menu while your game keeps playing in the background.

## Playlists

You can add new playlists to the GUI by scanning your game collection. Games will be sorted per system. You can also write your own playlists manually to display a list of your favorite games, or any list you can think of.

Playlist entries can be associated to a database entry to display the metadata of the game: Release Year, Genre, Developer, Number of Players, etc.

## Customizable

Customize the RetroArch GUI with options for thumbnails, dynamic backgrounds, shadows, animated backgrounds, icon themes, and more!

**Comment by markwkidd** [comment]
# https://www.retroarch.com/index.php?page=joypad-autoconfig

Note: this page URL includes the word "joypad". If it is important for consistency, maybe the URL could change to be `page=controller-autoconfig`, etc

## Joypad Auto Configuration
## Change to `Automatic Controller Mapping`

Common game controllers are automatically configured when plugged in, just like on a real game console.

Ideal to start a multiplayer game when a friend visits with their own controller.

You can also configure everything manually, assign special actions to combos, and more!

## How does it work?

RetroArch provides a set of configuration files for the most common controllers. Depending on your platform, these autoconfig profiles are either distributed with RetroArch or downloaded through the Online Updater.

When you plug in or wirelessly pair a controller for the first time, we try to find a matching profile in our set. Matching is done using 3 criteria: the device name, the vendor id and the product id. The `vendor id` and `product id` pair is often abbreviated as `vid:pid`. We compute a matching score for each configuration file based on these three factors. The autoconfig profile with the highest score is used to map the controller.

## Why is it needed?

RetroArch works on a lot of different platforms. Each of these platforms have one or more input systems. And these input systems differ widely in the way they enumerate the pad buttons.

Standalone emulators let you map each of your controls to the original controller for the emulated system. For example, this is how the OpenEMU controller configuration looks:

[Screenshot]

The difference is that RetroArch begins by detecting your controller and automatically configuring it if possible. Manual mapping as with standalone emulators is always an option, however!

### Benefits
* Plug and play with a new controller, without keyboard and mouse access needed for configuration and mapping.
* Plug many different controllers and have them attributed to each player like it would work on a real game console.
* Unplug the second controller, and replace it by another one, even if it's of a different brand and model.

## Joypad auto configuration profiles
## Change to: `Controller auto configuration profiles`

This is what a controller profile looks like in RetroArch.

The first part is used for matching, as explained above. The `vendor id` and `product id` are in decimal format.

The second part is the mapping itself, where each button is assigned to a button of the RetroPad (the RetroArch idealized controller abstraction).

The third part are *input descriptors* used by RetroArch to display the labels of the buttons as they are physically printed on your controller. For example: if you are using a DualShock pad, RetroArch will refer to the buttons as Cross, Circle, Square and Triangle.

## Downloading or updating joypad profiles
## Change to: `Updating controller profiles`

On platforms that allow the RetroArch Online Updater, you can update the set of controller profiles from the menu. Go to **Main Menu->Online Updater->Update Autoconfig Profiles** to get the latest version of the profile pack.

A yellow message will appear at the bottom of the screen showing the download progress and the extraction of the archive.

## Generating a joypad profile
## Change to: `Generating a controller profile`

If your controller is not recognized by RetroArch even after updating the profiles, or if RetroArch's matching profile is not suitable for you controller, you can generate a new profile to use.

The first step is to proceed to a manual mapping of your pad. For this, unplug all the other joypads, and use `Settings->Input->User 1 Binds->User 1 Bind All`. Make sure that your mapping is perfect by testing every button in the menu and in some games.

Then use `Settings->Inputs->User 1 Binds->User 1 Save Autoconfig` and the profile will be saved to your disk.

### Important note
You should now do a `Settings->Inputs->User 1 Binds->User 1 Bind Default All` to reset the manual settings. Otherwise they would take precedence over the profile you generated.

Unplug your controller an re-plug it. See if it is auto configured.

If you are happy with your profile, you can write the input descriptors part and submit your profile in our git repository at https://github.com/libretro/retroarch-joypad-autoconfig.

## Troubleshooting joypad autoconfig
**Change to: `Troubleshooting controller mappings`**

If for your controller is misconfigured by the automatic system, you may want to look at the RetroArch log [https://docs.libretro.com/guides/generating-retroarch-logs/]. The log will show if a profile has been selected for your controller, and the path of the selected profile.

**Comment by markwkidd** [comment]
@fpscan that is all the uses of joypad that I can find on the site right now. I hope my notes make sense, and let me know if you would like the edits in another format. Thank you!

**Comment by fpscan** [comment]
Hey, these are great. Thank you for your effort. I made the changes and it should be live near soon.

**Comment by markwkidd** [comment]
You are very welcome, and thanks for your help as well
