### ISSUE TITLE
404 in Scummvm docs 

### ISSUE THREAD

**Issue by isuftin** [libretro/docs#793]
**Describe the bug**
A link out to an external GitHub repository results in a 404

**Expected behavior/changes**
The link directs to a working URL

**Additional context**
The line with the errant link is: https://github.com/libretro/docs/blob/master/docs/library/scummvm.md?plain=1#L280

I visited the external repo and can't make out where that content may have gone.

**Comment by fpscan** [comment]
@RobLoach is it supposed to be this link https://github.com/RobLoach/libretro-database-scummvm/blob/master/manual-games.json instead what's written in the docs?

**Comment by RobLoach** [comment]
Those links are suppose to point to the RDB files in libretro-database, I believe. Looks like the doc link is using relative URLs, which may or may not work when not on the docs site.

**Comment by Slarky** [comment]
The [scummvm.zip](https://github.com/libretro/docs/blob/master/docs/library/scummvm.md?plain=1#L89) link doesn't work anymore, too
