### ISSUE TITLE
Dolphin Crashing in 6th and 7th gen Intel

### ISSUE THREAD

**Issue by DJZK** [libretro/docs#802]
**Describe the bug**
Gamecube Games crashing in RetroArch in 6th and 7th gen Intel

**Expected behavior/changes**
Games running smoothly and properly without crashes. Just like how it works with my 4th Gen (i5-4570S, i7-4770k)

**Additional context**
Games Tested:
SoulCalibur II Jap
SoulCalibur II Eng
Need for Speed Underground

Processors Tested that crashes:
i7-7500u
i7-7700HQ
i7-7700K
i7-7740x
i7-6700k

**Comment by hizzlekizzle** [comment]
Can you post a log of it crashing? This is the first I've heard of it, so I would be very surprised if something else isn't the culprit.

**Comment by DJZK** [comment]
Where can i see the logs?

**Comment by DJZK** [comment]
![image](https://user-images.githubusercontent.com/38833462/215800780-b6356861-4270-42c2-92e0-454e45ecf591.png)
Logs folder is empty

**Comment by hizzlekizzle** [comment]
there are a few ways to get a log, but the easiest is to go to settings > log and set both logging verbosities to DEBUG and 'log to file' to ON. Do whatever it takes to reproduce the offending behavior and then close RetroArch (if needed). It will then create a log file in your 'log' directory, which you can open in a text editor. If you want us to take a look at it, copy/paste the log contents somewhere like pastebin.com and then post a link to it here (this is more convenient for people than having to download it and open it in our own text editors)

**Comment by DJZK** [comment]
![image](https://user-images.githubusercontent.com/38833462/215802245-a0c30c49-cdb9-403b-a043-136a4434e5e9.png)
I just played right now, it crashed here. I was using the same driver as my 4th gen who is running GTX 1650. Im currently running GTX 1070. I tried swapping them both Graphics Cards, DDU and reinstalled drivers to isolate the problems better. it seem not to crash with the 4th gen. Heck im almost done with SoulCaliburII running it on my DIY Console (4th gen) running on Windows 10. But it seem crashing here at 6th and 7th gen

**Comment by DJZK** [comment]
Tried playing again, managed to finish a dungeon in Weapon Master. it crashed right in the battle when i started another one. Here's the log generated 

https://pastebin.com/3r9UAWVv

**Comment by DJZK** [comment]
It is also important to note that i was running the game on a NAS. But it does not fix anything moving it to local storage.

My 4th gen is also running the game on the same NAS but never crashed like this.

**Comment by hizzlekizzle** [comment]
Hmm, I don't really see anything too suspicious in there, particularly not in the second one. Does it treat you any differently if you switch to d3d11 for your video driver?

**Comment by DJZK** [comment]
I'm as confused as well. And no, it does not change it switching to different video drivers. I even tried directly copying the cfg file from my 4th gen to see if i have messed up something else in this 7th gen. To no luck

**Comment by fpscan** [comment]
Hi,

I'm not sure if it's right place to ask, wouldn't be https://github.com/libretro/dolphin more correct?

**Comment by DJZK** [comment]
The standalone dolphin works fine though. Which why i asked here

**Comment by hizzlekizzle** [comment]
That's the repo for the libretro fork, not for the upstream dolphin emulator.

That would probably be a better place for this, indeed, since it is almost certainly a core issue, if anything, rather than a frontend issue.

**Comment by DJZK** [comment]
right! I'll post this issue there.
