### ISSUE TITLE
Android Installation via F-Droid has an invalid repository link

### ISSUE THREAD

**Issue by Kenny-MWI** [libretro/docs#952]
**Describe the bug**
On [this page](https://docs.libretro.com/guides/install-android/#installation-via-f-droid) there are instructions for installing the app via F-Droid. A QR code and repository link are provided for the adding the repo to F-Droid but neither option work. The provided link is `https://fdroid.libretro.com`.  The error message on F-Droid says it's an invalid repository and to "contact the maintainer and let them know about the issue." 

**Expected behavior/changes**
I would expect the QR code and link to be valid and allow the repository to be added to F-Droid. I believe the URL should be `https://fdroid.libretro.com/repo/` after a little more digging. 

**Additional context**
I think the builds in the libretro repo are old. After adding the using the link I found, F-Droid has a notice on RetroArch saying it was built for an old version of Android and cannot be updated automatically. It says it was last updated 4 years ago. 

I also notice it seems to be available in the normal F-Droid repo and was last updated 10 days ago.  So maybe the Android documentation should be updated to remove the libretro repo instructions?

**Comment by hizzlekizzle** [comment]
> So maybe the Android documentation should be updated to remove the libretro repo instructions?

Yeah, this.
