### ISSUE TITLE
for Linux_arm32？

### ISSUE THREAD

**Issue by 2494654220** [libretro/docs#994]
How to build a core suitable for Linux_arm32? I want to use it for the EMUELEC system. I have tried multiple compilation methods, but the SO core I created cannot be used

**Comment by gouchi** [comment]
Hi,

It is more related to [EmuELEC](https://github.com/EmuELEC/EmuELEC/tree/master_32bit?tab=readme-ov-file#emuelec) build system as we don't provide arm build.

You will need to use [master_32bit branch](https://github.com/EmuELEC/EmuELEC/tree/master_32bit) of EmuELEC.

Build setup

```
sudo apt update && sudo apt upgrade
sudo apt-get install gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf xmlstarlet
git clone https://github.com/shantigilbert/EmuELEC.git EmuELEC    
cd EmuELEC  
git checkout master_32bit  
```

Depending of your [device](https://github.com/EmuELEC/EmuELEC/tree/master_32bit/projects), you should build the [package](https://github.com/EmuELEC/EmuELEC/tree/master_32bit/packages/emulation) with something for Amlogic devices
```
PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC scripts/clean package-name
PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC scripts/build package-name
```

Please close this issue.

Thank you.
