### ISSUE TITLE
[Question] clarify "cores" 

### ISSUE THREAD

**Issue by freedom-foundation** [libretro/docs#998]
Now looking into [RetroArch](https://github.com/freedom-foundation/RetroArch) to clarify if "cores" correspond to chip designes or if they are only verbatim. Do "cores" correspond to CPU designes of the labled systems?

**Comment by freedom-foundation** [comment]
yes and the jargon "emulator" would include a CPU does a core have a CPU design which it then emulates?

**Comment by freedom-foundation** [comment]
> Most (but not all) libretro cores exist in the [libretro organization](https://github.com/libretro) as forks of the original emulators. You can check either these forks or the original repository for details about how the CPU is implemented, although the specifics will depend on the core.

Yeah but there are 282 repos there how would I find the code of a specific CPU. For example the Game Boy original sharp CPU, and neccesirly the memory and bus.

**Comment by hizzlekizzle** [comment]
You'd have to just go through them. For example, Gambatte's is in libgambatte/src/cpu.cpp.

**Comment by freedom-foundation** [comment]
> You'd have to just go through them. For example, Gambatte's is in libgambatte/src/cpu.cpp.

Looking at it now. What is this a Game Boy CPU is this supposed to emulate the Sharp SM83?

**Comment by hizzlekizzle** [comment]
Yeah, something like that. https://www.reddit.com/r/EmuDev/comments/gm5bhf/comment/fr1w5lv/

**Comment by freedom-foundation** [comment]
> Yeah, something like that. https://www.reddit.com/r/EmuDev/comments/gm5bhf/comment/fr1w5lv/

PG – Parental Guidance Suggested 
          Reddit can be rather illuminating.

**Comment by freedom-foundation** [comment]
"core" is a RetroArch jargon. A core is a fork of another emulator stripped of IO so that RetroArch can handle it. So then:
 "core" is an emulator stripped of IO and imported into RetroArch.

**Comment by freedom-foundation** [comment]
> Yeah, something like that. https://www.reddit.com/r/EmuDev/comments/gm5bhf/comment/fr1w5lv/

I had some interest in FPGA and just seeing if an emulator can achieve the same.
